### ISSUE TITLE
Missing Translation: BC/French/Welcome to BC/Public Transportation topic

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1756]
I expected to go to BC/French/Bienvenue en CB/Public Transportation topic and see the topic title written in French. Instead it is in English.

<img src="https://images.zenhubusercontent.com/60b823128e6f424e93549168/dc564cdc-a88d-4e89-842a-45e880abc0a1" width=300 align=centre><br>

### Acceptance Criteria 
- [x]  Change "Public Transportation" to French "Transport public".

### Steps for QA: 
1.  Go to topics
2. Click on "Bienvenue en CB"
3. Look for "Transport public" and make sure it doesn't still say "Public Transportation"

**Comment by alysha-PG** [comment]
fixed.

**Comment by rasmus-storjohann-PG** [comment]
This issue is still there, testing version 1.89.0 on Andoid, MB release candidate

**Comment by rasmus-storjohann-PG** [comment]
Reversing my re-opening of this issue, the problem is tracked here https://github.com/pg-irc/pathways-frontend/issues/1757
